name: InventoryItemInterface
version: '${project.version}'
main: jp.mrik.inventoryiteminterface.InventoryItemInterface
api-version: '1.20'
authors: [ Mr_IK ]
depend: [TimerThreadTools]
description: InventoryItemInterface
